Feat: 인기 멍멍이 피드 추천 API, 이미지 처리 관련 S3 연결
DevOcean-2/backend-feed pull request #3
Opened 2024-11-18 13:07 UTC by namkidong98

### 인기 멍멍이 피드 추천 API 개발
- /feed/posts/famous
- 좋아요 개수를 기준으로 내림차순 정렬해서 상위 5개 피드 반환

### 이미지 처리 관련 S3 연결
- post create에서 이미지의 base64 encoding string을 입력받아서 s3에 업로드
- list에서도 S3 URL이 리스트 형태로 잘 반환되는 것을 확인

2024-11-18 13:53 UTC, changjjjjjjj commented on app/models/post.py
> +    __tablename__ = "users"
유저서비스랑 테이블 이름 겹치지 않나요?

2024-11-18 14:02 UTC, changjjjjjjj commented
별개로 다른 기능들은  pr을 나눠서 올리면 리뷰할 때 더 편합니다ㅎㅎ

2024-11-18 14:08 UTC, namkidong98 commented
죄송합니다 제가 이런 경험이 많이 부족해서...그러면 구현 기능별로 commit하고 pr하고 commit하고 pr하고 하는 식으로 하는 것일까요?

2024-11-18 14:20 UTC, changjjjjjjj requested changes

2024-11-18 14:20 UTC, changjjjjjjj commented on app/routers/post.py
> +    # token.jwt_required()
이거 주석처리는 테스트용으로 하셨던 것 같은데 맞을까요?

2024-11-18 14:20 UTC, changjjjjjjj commented on app/routers/post.py
> +    # token.jwt_required() # 인증이 필요 없지 않을까?
웬만하면 모든 api에 넣으려고 합니다!

2024-11-18 14:20 UTC, changjjjjjjj commented on app/services/post.py
> +def famous_posts(db: Session) -> List[PostResponse]:
기획이었나 프론트쪽에서 랜덤하게 5개를 요청했었던 것으로 기억하는데 상위 100개 정도 중에 랜덤하게 5개 보내는 식으로 보완하면 어떨까요

2024-11-18 14:20 UTC, changjjjjjjj commented on app/services/post.py
>          db.delete(post)
db를 먼저 날리고 이미지를 지우고 이미지 지우기 실패시 롤백하는게 맞지 않을까 합니다

2024-11-18 14:20 UTC, changjjjjjjj commented on app/services/post.py
> +def create_s3_client():
이런건 util로 빼면 좋을 것 같아요

2024-11-18 14:20 UTC, changjjjjjjj commented on app/services/post.py
> +        aws_access_key_id=os.getenv("AWS_ACCESS_KEY"),
저희 지금 레포지토리 세팅에 secrets and variables 보면 AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY가 있어요. 이 값을 Dockerfile과 .github/ci.yaml을 통해서 빌드할 때 넣어줄 수 있는데 place랑 아마 user도 세팅 다 해놨을테니 한번 보고 참고하셔서 수정해보면 좋을 것 같아요.

2024-11-18 14:20 UTC, changjjjjjjj commented on app/services/post.py
> +            UserTable.name.label('user_name'),
일단 동작은 되게 짜셨을테니 뭐..넘어가지만 이렇게 유저서비스의 db를 건드는건 msa에 좀 안 맞는 구현이라 생각합니다. user쪽 api를 호출해서 처리하는게 맞을 것 같아요. 참고만 해주세요

2024-11-18 14:22 UTC, changjjjjjjj commented
> 죄송합니다 제가 이런 경험이 많이 부족해서...그러면 구현 기능별로 commit하고 pr하고 commit하고 pr하고 하는 식으로 하는 것일까요?

@namkidong98 기능별로 브랜치를 따고 pr을 여러개 날리면 됩니다ㅎㅎ 브랜치 이름을 kidong보다는 기능을 알 수 있게 지으면 더 좋고요.

2024-11-18 14:24 UTC, namkidong98 commented on app/routers/post.py
> +    # token.jwt_required() # 인증이 필요 없지 않을까?
넵 알겠습니다!

2024-11-18 14:26 UTC, namkidong98 commented on app/services/post.py
> +def create_s3_client():
넵!

2024-11-18 14:27 UTC, namkidong98 commented on app/services/post.py
> +        aws_access_key_id=os.getenv("AWS_ACCESS_KEY"),
넵 알겠습니다!

2024-11-18 14:28 UTC, namkidong98 commented on app/services/post.py
> +def famous_posts(db: Session) -> List[PostResponse]:
그게 좋을 것 같습니다!

2024-11-18 14:29 UTC, changjjjjjjj commented on app/models/post.py
> +    __tablename__ = "users"
유저테이블 그대로 가져온 것으로 전달받아 resolved 처리

2024-11-18 14:30 UTC, namkidong98 commented on app/services/post.py
> +            UserTable.name.label('user_name'),
그렇군요...다음부터는 조심하도록 하겠습니다. 그리고 가능하다면 다음번에 user쪽 api 호출해서 처리하는 방식으로 변경하도록 하겠습니다.

2024-11-18 14:32 UTC, namkidong98 commented on app/routers/post.py
> +    # token.jwt_required()
죄송합니다 다음부터는 꼼꼼히 체크하도록 하겠습니다.

2024-11-18 14:32 UTC, changjjjjjjj commented on app/services/post.py
> +            UserTable.name.label('user_name'),
넹 급한건 아니니 발표 전까지 시간 되시면 공부 겸 구현 변경해보면 좋을 것 같습니다

2024-11-18 14:34 UTC, namkidong98 commented
> > 죄송합니다 제가 이런 경험이 많이 부족해서...그러면 구현 기능별로 commit하고 pr하고 commit하고 pr하고 하는 식으로 하는 것일까요?
> 
> @namkidong98 기능별로 브랜치를 따고 pr을 여러개 날리면 됩니다ㅎㅎ 브랜치 이름을 kidong보다는 기능을 알 수 있게 지으면 더 좋고요.

그렇게 하는거군요 감사합니다!

2024-11-18 14:34 UTC, changjjjjjjj commented on app/routers/post.py
> +    # token.jwt_required()
스터디에서 죄송할 것까진 없어요 기동님...맘편히 수정해주세요...

2024-11-19 04:31 UTC, changjjjjjjj requested changes
수정하신 부분들은 문제 없어보입니다! 추가로 확인해주셔야 할 부분은
1. make lint 실행해서 수정 부탁드려요. import error랑 not callable도 있어서
2. pr의 경우 아직 메인 브랜치에 적용된 내용이 아니라 fix commit이 있을 필요가 없어요. pr을 수정하실 때는 reset, force push를 이용해서 커밋 하나로 유지해주세요. 아니면 squash 후 force push 하시면 됩니다

2024-11-19 04:31 UTC, changjjjjjjj commented on app/utils/image.py
> +        bucket_name = 'balm-bucket'
범용적으로 쓰는 util 함수이니 다음부터는 이런 건 파라미터로 받을 수 있도록 짜면 더 좋을 것 같아요

2024-11-19 05:30 UTC, namkidong98 commented on app/utils/image.py
> +        bucket_name = 'balm-bucket'
넵! 반영하도록 하겠습니다

2024-11-19 05:36 UTC, changjjjjjjj approved these changes
lgtm

2024-11-19 05:37 UTC, merged